services:
  postgresql:
    image: "bitnami/postgresql:16"
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=todos_dev

volumes:
  postgresql_data:
    driver: local
